/** Public, owner-supplied facts. The original résumé remains unchanged. */
export const knowledge = [
  {
    id: "intro",
    title: "Overview",
    source: "Profile & résumé",
    keywords: [
      "who",
      "introduce",
      "summary",
      "yourself",
      "subramanian",
      "overview",
      "background",
    ],
    text: "Subramanian M is an AI Engineer based in Coimbatore, India. He builds practical RAG systems, AI agents, LLM applications and production-oriented backends. His path started with freelance video editing in 2020, moved into Python and full-stack development around 2022, and then into machine learning and AI engineering.",
  },
  {
    id: "skills",
    title: "Technical skills",
    source: "Profile & résumé",
    keywords: [
      "skill",
      "stack",
      "technolog",
      "strong",
      "python",
      "typescript",
      "language",
      "technical",
      "expertise",
      "programming",
    ],
    text: "His strongest areas are Python, RAG and Agentic RAG, multimodal retrieval, LangChain, LangGraph, AI agents, tool calling, hybrid search, reranking, embeddings and vector search. He also works with FastAPI, PostgreSQL, React/Next.js, Docker and LLM APIs. His résumé includes TypeScript, JavaScript, TensorFlow, PyTorch, Hugging Face, scikit-learn, FAISS, Linux, REST APIs and webhooks.",
  },
  {
    id: "rag",
    title: "RAG & retrieval",
    source: "Profile & résumé",
    keywords: [
      "rag",
      "retriev",
      "embedding",
      "vector",
      "multimodal",
      "rerank",
      "hybrid",
      "faiss",
      "langchain",
    ],
    text: "Subramanian works with RAG, Agentic RAG and multimodal RAG. His experience includes hybrid retrieval combining dense semantic and lexical search, reranking, and retrieving images alongside text while preserving document/page source metadata. He uses LangChain Runnables and LangGraph to keep ingestion, retrieval and generation modular. The advanced RAG portfolio chatbot in his résumé is described as in development, not a finished deployment.",
  },
  {
    id: "agents",
    title: "Agents & stateful applications",
    source: "Profile & résumé",
    keywords: [
      "agent",
      "langgraph",
      "tool call",
      "memory",
      "stateful",
      "human",
      "persistent",
      "stream",
      "orchestrat",
    ],
    text: "He has experience with LangGraph, tool calling, persistent conversations, human-in-the-loop workflows, streaming responses, external tools and database-backed memory. He has designed multi-step tool workflows, custom API endpoints, webhook handlers, timezone-aware scheduling and defensive parsing of model/tool payloads.",
  },
  {
    id: "production",
    title: "Production experience",
    source: "Résumé",
    keywords: [
      "production",
      "deploy",
      "lazyloop",
      "voice",
      "receptionist",
      "built",
      "build",
      "experience",
      "end to end",
      "shipped",
      "real world",
      "hands on",
      "backend",
      "infrastructure",
      "fastapi",
      "postgres",
      "docker",
      "linux",
    ],
    text: "His résumé describes building and operating LazyLoop, an independent AI voice receptionist product. It handles inbound calls, checks Google Calendar and books appointments through tool-calling workflows. He owned conversation architecture, integrations, PostgreSQL and deployment across Hetzner, Docker, Coolify and Vercel. He also built an LLM-assisted pipeline for approximately 20,000 business records using self-hosted Firecrawl and Gemini 2.5 Flash, and debugged browser-pool, SQL and WebRTC/CSP failures. This is independent product experience, not employment at a company named LazyLoop.",
  },
  {
    id: "creative",
    title: "Freelance & creative background",
    source: "Profile & résumé",
    keywords: [
      "freelance",
      "fiverr",
      "client",
      "video",
      "color",
      "creative",
      "editing",
      "reviews",
      "earned",
      "500",
      "remote experience",
      "career change",
      "transition",
      "2020",
      "2022",
    ],
    text: "He started freelancing as a video editor and colorist in 2020, working remotely with international clients. His supplied profile reports 5+ years of remote client experience, 100+ five-star Fiverr reviews, $7,000+ earned on Fiverr, 500+ video projects delivered/exported and previous Fiverr’s Choice recognition. His résumé lists 130 Fiverr orders and 72 clients. The 500+ figure includes work outside Fiverr and video exports; it should not be presented as 500 Fiverr orders. He moved into software development around 2022.",
  },
  {
    id: "education",
    title: "Education & certification",
    source: "Résumé",
    keywords: [
      "education",
      "degree",
      "college",
      "university",
      "bca",
      "ignou",
      "certif",
      "tensorflow",
      "diploma",
      "vfx",
      "studied",
      "qualification",
    ],
    text: "His résumé lists a Bachelor of Computer Applications at Indira Gandhi National Open University (IGNOU), 2019–2021; a Diploma in 3D & VFX from Image Institute, 2021; and the Google TensorFlow Developer Certificate, 2023. The certificate date is historical; current renewal or validity is not specified.",
  },
  {
    id: "opportunities",
    title: "Roles & availability",
    source: "Profile",
    keywords: [
      "hire",
      "hiring",
      "job",
      "role",
      "opportunit",
      "available",
      "remote",
      "relocat",
      "international",
      "career",
      "fit",
      "looking",
      "recruit",
      "work together",
    ],
    text: "Subramanian is interested in AI Engineer, Applied AI Engineer and LLM Engineer roles. He is open to opportunities in India, remote roles and international opportunities. His goal is end-to-end AI engineering: taking a system from experimentation to a reliable deployed product. His notice period, salary expectations, visa/work authorization and relocation commitments are not supplied; contact him directly for those details.",
  },
  {
    id: "learning",
    title: "Current focus",
    source: "Profile",
    keywords: [
      "learn",
      "current focus",
      "roadmap",
      "mlops",
      "kubernetes",
      "fine tun",
      "finetun",
      "inference",
      "transformer",
      "dsa",
      "system design",
      "improv",
      "next",
    ],
    text: "He is currently strengthening MLOps, model deployment, Docker and Kubernetes, LLM fine-tuning and inference, Transformers, AI system design and basic-to-intermediate DSA. These are active learning areas, not claims of established expertise. He plans to build 2–3 strong live AI projects and share technical work regularly on LinkedIn.",
  },
  {
    id: "location",
    title: "Location",
    source: "Profile & résumé",
    keywords: [
      "where",
      "location",
      "based",
      "live",
      "coimbatore",
      "india",
      "timezone",
    ],
    text: "Subramanian is based in Coimbatore, Tamil Nadu, India (India Standard Time, UTC+5:30). He is open to opportunities in India, remote roles and international opportunities.",
  },
  {
    id: "contact",
    title: "Contact & links",
    source: "Profile & résumé",
    keywords: [
      "contact",
      "email",
      "reach",
      "social",
      "linkedin",
      "github",
      "connect",
      "resume",
      "résumé",
      "download",
      "cv",
    ],
    text: "Email: suryasubramanian252@gmail.com. GitHub: https://github.com/subramanian252. LinkedIn: https://www.linkedin.com/in/subramanian-m-9aa117227/. Fiverr: https://www.fiverr.com/subramanian007. Use the Download résumé button on this page for his original PDF résumé.",
  },
  {
    id: "projects",
    title: "Portfolio projects",
    source: "Portfolio",
    keywords: [
      "project",
      "portfolio",
      "travel",
      "writer",
      "llm chat",
      "demo",
      "interactive",
      "live project",
    ],
    text: "LazyChat is a completed portfolio case study with source code available on GitHub; its public live chat is not deployed yet. Subramanian built its FastAPI, LangGraph, SQLite and FAISS backend, including document RAG, selectable OpenRouter models, tool calling, persistent conversations, human approval and usage tracking. The React frontend was built with AI under his direction and supervision. Travel Planner and Agentic Writer remain coming-soon ideas.",
  },
] as const;

export const suggestedQuestions = [
  "What does he build?",
  "What’s his tech stack?",
  "Tell me about his background",
  "Is he open to opportunities?",
];

export const profileContext = knowledge
  .map((k) => `[${k.title} | ${k.source}]\n${k.text}`)
  .join("\n\n");
